# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# user1 = User.create!(first_name: 'Michael', last_name: 'Scott', email: 'mscott@mail.com', password: 'michael')
# user2 = User.create!(first_name: 'Dwight', last_name: 'Schrute', email: 'dschrute@mail.com', password: 'dwight')


business1 = Business.create!(name: "MILK+T", address: "310 E 2nd St", city: "Los Angeles", state: "CA", zip_code: "90012", phone_number: "(323) 884-1164", website: "http://www.milkandt.com", open: "12:00PM", close: "10:00PM", category: "Bubble Tea", price: "$")
business2 = Business.create!(name: "Dingle Berries Coffee and Tea", address: "8036 W 3rd St", city: "Los Angeles", state: "CA", zip_code: "90048", phone_number: "(323) 413-2604", website: "https://dingleberriescoffeeandtea.com", open: "12:00PM", close: "7:00PM", category: "Bubble Tea", price: "$")
business3 = Business.create!(name: "Bao Dim Sum House", address: "8256 Beverly Blvd", city: "Los Angeles", state: "CA", zip_code: "90048", phone_number: "(323) 655-6556", website: "http://www.baodimsum.com/", open: "12:00PM", close: "9:00PM", category: "Dim Sum", price: "$$")
business4 = Business.create!(name: "Zzamong", address: "4355 W 3rd St", city: "Los Angeles", state: "CA", zip_code: "90004", phone_number: "(213) 739-2747", website: "http://zzamongrestaurant.com", open: "11:30AM", close: "9:30PM", category: "Korean", price: "$$")
business5 = Business.create!(name: "Kang Ho-dong Baekjong", address: "3465 W 6th St, Ste 20", city: "Los Angeles", state: "CA", zip_code: "90020", phone_number: "(213) 384-9678", website: "http://www.baekjeongktown.com", open: "11:30AM", close: "1:30AM (Next day)", category: "Barbeque", price: "$$$")
business6 = Business.create!(name: "Yuk Dae Jang", address: "3033 W 5th St, Ste 104-105", city: "Los Angeles", state: "CA", zip_code: "90020", phone_number: "(213) 352-1331", website: "https://yukdaejanglosangeles.mybistro.online/", open: "10:00AM", close: "9:00PM", category: "Korean", price: "$$")
business7 = Business.create!(name: "Leo's Taco Truck", address: "1515 S La Brea Ave", city: "Los Angeles", state: "CA", zip_code: "90019", phone_number: "(323) 346-2001", website: "http://www.leostacostruck.com", open: "10:00AM", close: "2:00AM (Next day)", category: "Food Trucks", price: "$")
business8 = Business.create!(name: "Tacos 1986", address: "609 S Spring St", city: "Los Angeles", state: "CA", zip_code: "90014", phone_number: "(213) 988-7202", website: "https://www.tacos1986.com", open: "11:00AM", close: "12:00AM (Next day)", category: "Tacos", price: "$")
business9 = Business.create!(name: "BurgerShop", address: "724 S Spring St", city: "Los Angeles", state: "CA", zip_code: "90014", phone_number: "(213) 267-6993", website: "https://www.burgershopca.net", open: "11:00AM", close: "9:00PM", category: "Burgers", price: "$$")
business10 = Business.create!(name: "Masa of Echo Park", address: "1800 W Sunset Blvd", city: "Los Angeles", state: "CA", zip_code: "90026", phone_number: "(213) 989-1558", website: "https://www.masaofechopark.com", open: "1:00PM", close: "8:00PM", category: "Pizza", price: "$$")
business11 = Business.create!(name: "La Pergoletta", address: "1802 Hillhurst Ave", city: "Los Angeles", state: "CA", zip_code: "90027", phone_number: "(323) 664-8259", website: "http://www.lapergoletta.com", open: "12:00PM", close: "10:00PM", category: "Italian", price: "$$")
business12 = Business.create!(name: "Full Moon House", address: "960 N Hill St", city: "Los Angeles", state: "CA", zip_code: "90012", phone_number: "(213) 537-0792", website: "https://fullmoonhouserestaurantinla.weebly.com/", open: "11:00AM", close: "12:00AM (Next day)", category: "Chinese", price: "$$")
business13 = Business.create!(name: "Hae Ha Heng Thai Bistro", address: "301 S Western Ave, Ste 209", city: "Los Angeles", state: "CA", zip_code: "90020", phone_number: "(213) 388-2407", website: "http://www.myhaehaheng.com", open: "11:00AM", close: "10:00PM", category: "Thai", price: "$$")
business14 = Business.create!(name: "Lee's Key and Locksmith", address: "3120 3 8th St", city: "Los Angeles", state: "CA", zip_code: "90005", phone_number: "(213) 437-9531", website: "http://leeskeylocksmith.com", open: "9:00AM", close: "5:00PM", category: "Keys & Locksmiths", price: "$$")
business15 = Business.create!(name: "Community Auto Center", address: "6800 Melrose Ave", city: "Los Angeles", state: "CA", zip_code: "90038", phone_number: "(323) 932-6141", website: "https://www.communityautocenterca.com/", open: "8:00AM", close: "6:00PM", category: "Auto Repair", price: "$$")
business16 = Business.create!(name: "Thirsty Crow", address: "2939 W Sunset Blvd", city: "Los Angeles", state: "CA", zip_code: "90026", phone_number: "(323) 661-6007", website: "http://www.thirstycrowbar.com/", open: "5:00PM", close: "2:00AM (Next day)", category: "Bars", price: "$$")
business17 = Business.create!(name: "Bacari Silverlake", address: "3636 Sunset Blvd", city: "Los Angeles", state: "CA", zip_code: "90026", phone_number: "(323) 928-2098", website: "https://www.bacarisilverlake.com/", open: "5:00PM", close: "12:00AM (Next day)", category: "Mediterranean", price: "$$")
business18 = Business.create!(name: "Woodcat Coffee Bar", address: "1532 W Sunset Blvd", city: "Los Angeles", state: "CA", zip_code: "90026", phone_number: "(213) 537-0147", website: "http://www.woodcatcoffee.com", open: "6:30AM", close: "6:00PM", category: "Coddee & Tea", price: "$$")
business19 = Business.create!(name: "India's Restaurant", address: "4366 Fountain Ave", city: "Los Angeles", state: "CA", zip_code: "90029", phone_number: "(323) 912-9230", website: "http://www.indiasrestaurant.net/", open: "11:00AM", close: "1:00AM (Next day)", category: "Indian", price: "$")
business20 = Business.create!(name: "Pho 87", address: "1019 N Broadway", city: "Los Angeles", state: "CA", zip_code: "90012", phone_number: "(323) 227-0758", open: "11:00AM", close: "8:00PM", category: "Vietnamese", price: "$$")
business21 = Business.create!(name: "Granville", address: "8701 Beverly Blvd", city: "Los Angeles", state: "CA", zip_code: "90048", phone_number: "(424) 522-5161", website: "http://www.granville.net", open: "11:30AM", close: "9:00PM", category: "American", price: "$$")
business22 = Business.create!(name: "M Grill", address: "3832 Wilshire Blvd", city: "Los Angeles", state: "CA", zip_code: "90010", phone_number: "(213) 389-2770", website: "http://www.m-grill.com/", open: "5:30PM", close: "9:30PM", category: "Brazilian", price: "$$$$")
business23 = Business.create!(name: "In-N-Out Burger", address: "7009 Sunset Blvd", city: "Los Angeles", state: "CA", zip_code: "90028", phone_number: "(800) 786-1000", website: "http://www.in-n-out.com", open: "10:30AM", close: "1:00AM (Next day)", category: "Fast Food", price: "$")
business24 = Business.create!(name: "Oakobing", address: "3300 W 6th St", city: "Los Angeles", state: "CA", zip_code: "90020", phone_number: "(213) 387-1002", website: "https://www.oakobing.com", open: "1:00PM", close: "11:00PM", category: "Shaved Ice", price: "$$")
business25 = Business.create!(name: "Milk Jar Cookies", address: "5466 Wilshire Blvd", city: "Los Angeles", state: "CA", zip_code: "90036", phone_number: "(323) 634-9800", website: "http://www.milkjarcookies.com/", open: "11:00AM", close: "4:00PM", category: "Desserts", price: "$")

